name: scp files
on:
  push:
    branches: [main]
jobs:
  build:
    name: Deployment and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install and npm run build (Theme)
        run: |
          npm install
          npm run build
      - name: copy file via ssh password
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: hJqDe60r8EtiYb6b
          # port: ${{ secrets.PORT }}
          port: 222
          source: "./"
          target: ${{ secrets.TARGET }}
