name: Deploy to Hetzner Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Debes agregar la clave privada SSH como un secreto en la configuración de GitHub

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Personaliza la versión de Node.js que necesitas

      - name: Install project dependencies
        run: |
          npm install
          composer install

      - name: Deploy to Hetzner
        run: |
          scp -P 222 ./meraki_theme expero@dedi5235.your-server.de:public_html/wp-content/themes/Meraki
