name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: # Define la variable de entorno MY_PORT
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configura SSH
        uses: webfactory/ssh-agent@v0.7.0

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliega en servidor
        run: |
          # En este punto, puedes usar $MY_PORT para referirte al puerto en tu código o comandos.
          echo "El puerto configurado es: $MY_PORT"
          # Ejecuta tus comandos de despliegue aquí, utilizando $MY_PORT según sea necesario.
