name: scp files
on:
  push:
    branches: [main]
jobs:
  build:
    name: Deployment and Build
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@master
      - name: npm install and npm run build (Theme)
        run: |
          npm install
          npm run build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: ${{ secrets.TARGET }}
